exports.msgEnum = {
  LOGIN_SUCCESS: "Đăng nhập thành công",
  LOGIN_FAIL: "Đăng nhập thất bại",
  MAIL_SENT: "Liên kết đặt lại mật khẩu đã được gửi đến email của bạn",
  USER_NOT_FOUND: "Mã sinh viên không tồn tại",
  RESET_PASSWORD_SUCCESS: "Khôi phục mật khẩu thành công",
  RESET_PASSWORD_FAIL: "Mã không hợp lệ",
  CHANGE_PASSWORD_SUCCESS: "Đổi mật khẩu thành công",
  ADD_SUCCESS: "Thêm thành công",
  DELETE_SUCCESS: "Xóa thành công",
  DELETE_FAIL: "Xóa thất bại",
  UPLOAD_SUCCESS: "Upload thành công",
  WRONG_FILE_TYPE: "Định dạng tệp tin không được phép tải lên",
  FILE_SIZE_OVER: "Kích thước tệp tin vượt quá quy định",
  UPLOAD_FAIL: "Tải lên thất bại",
  SERVER_ERROR: "Lỗi máy chủ",
  DUPLICATE_VALUE: "Trùng dữ liệu",
  DATA_NOT_FOUND: "Không tìm thấy dữ liệu",
  TOKEN_INVALID: "Token không hợp lệ",
  TOKEN_NOT_FOUND: "Không tìm thấy token",
  UPDATE_SUCCESS: "Cập nhật thành công",
  USER_NOT_FOUND: "Người dùng không tồn tại",
  USER_EXIST: "User had already existed",
  WRONG_PASSWORD: "Mật khẩu không đúng",
  CURRENT_PASSWORD_INVALID: "Mật khẩu hiện tại không hợp lệ",
  NEW_PASSWORD_INVALID: "Mật khẩu mới không hợp lệ",
  NOT_PERMISSION_DELETE: "Không được phép xóa",
  FAIL_FORMAT: "Dữ liệu không đúng định dạng",
  INVALID_PASSWORD: "Vui lòng nhập mật khẩu mới",
  INVALID_OLD_PASSWORD: "Vui lòng nhập mật khẩu cũ",
  UNAUTHORIZED: "Không được phép để truy cập route này",
  PRODUCT_NOT_FOUND: "Không có sản phẩm",
};
